apiVersion: v1
kind: Service
metadata:
  name: spinhttp
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: spinhttp 
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: spinhttp 
  name: spinhttp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: spinhttp
  strategy: {}
  template:
    metadata:
      labels:
        service: spinhttp
    spec:
      containers:
        - name: spinhttpsrv
          image: arielszekely/spinhttpsrv:latest
          args:
          - "10"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1000m
            limits:
              cpu: 1000m
      restartPolicy: Always
status: {}
