apiVersion: v1
kind: Pod
metadata:
  name: netperf-1
spec:
  containers:
  - name: netperf
    image: arielszekely/netperf
    resources:
      requests:
        cpu: 2100m
  imagePullSecrets:
  - name: regcred
  restartPolicy: Never
