apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spinhttp-autoscale 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spinhttp 
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 1
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 1
      selectPolicy: Max
